DROP TABLE IF EXISTS users, requests, items, bookings, feedbacks;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists requests
(
    id           bigint generated by default as identity primary key,
    description  varchar(512)             not null,
    requester_id bigint references users (id),
    created_date timestamp with time zone not null
);

create table if not exists items
(
    id           bigint generated by default as identity primary key,
    name         varchar(255) not null,
    description  varchar(512) not null,
    owner_id     bigint references users (id) on delete cascade,
    is_available boolean      not null,
    request_id   bigint references requests (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    booker_id  BIGINT                                  NOT NULL,
    start_time TIMESTAMP without time zone             NOT NULL,
    end_time   TIMESTAMP without time zone             NOT NULL,
    status     VARCHAR(16)                             NOT NULL,
    CONSTRAINT PK_BOOKING PRIMARY KEY (id),
    CONSTRAINT FK_BOOKING_ITEM FOREIGN KEY (item_id) references items
        on delete cascade on update cascade,
    CONSTRAINT FK_BOOKING_BOOKER FOREIGN KEY (booker_id) references users
        on delete cascade on update cascade
);

CREATE TABLE IF NOT EXISTS feedbacks
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content      VARCHAR(512)                            NOT NULL,
    item_id      BIGINT                                  NOT NULL,
    author_id    BIGINT                                  NOT NULL,
    created_date TIMESTAMP without time zone             NOT NULL,
    CONSTRAINT PK_COMMENT PRIMARY KEY (id),
    CONSTRAINT FK_COMMENT_ITEM FOREIGN KEY (item_id) references items
        on delete cascade on update cascade,
    CONSTRAINT FK_COMMENT_AUTHOR FOREIGN KEY (author_id) references users
        on delete cascade on update cascade
)